# Generated by Django 2.2.6 on 2020-04-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psu_base', '0012_fakiresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_code', models.CharField(help_text='Application that this error belongs to.', max_length=15, verbose_name='Application Code')),
                ('path', models.CharField(help_text='This holds the path on which the error occurred', max_length=128)),
                ('parameters', models.CharField(blank=True, help_text='This holds the request parameters', max_length=500, null=True)),
                ('code_detail', models.CharField(blank=True, help_text='file, function, and line number of error', max_length=128, null=True)),
                ('sso_user', models.CharField(blank=True, help_text='This holds the logged-in user (which could be a provisional email address)', max_length=128, null=True)),
                ('impersonated_user', models.CharField(blank=True, help_text='This holds the impersonated user (which could be a provisional email address)', max_length=128, null=True)),
                ('proxied_user', models.CharField(blank=True, help_text='This holds the proxied user (which could be a provisional email address)', max_length=128, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='N', help_text='Indicates the status of the error (New, Ignored, Resolved)', max_length=1)),
                ('error_friendly', models.CharField(blank=True, help_text='Error that the user saw', max_length=128, null=True)),
                ('error_system', models.CharField(blank=True, help_text='Actual system error', max_length=128, null=True)),
            ],
        ),
    ]
